### ISSUE TITLE
[feature request] add link to each section for better sharing

### ISSUE THREAD

**Issue by jdoubleu** [TypeRocket/docs#6]
I often find myself where I want to share a section from your documentation with someone else. Unfortunately it is quiet cumbersome to get a link to the current section.

Right now, I have to scroll up all the way to the _table of contents_, click on the section link, which takes me to the section I want to share and then copy the url from my address bar.

It would be nice, if you could also add a link behind the section header, or at least behind the `#` sign. This way I would be able to right-click the header/`#` and copy the url from my browsers context menu.

This is a common feature among most documentations. Take GitHub's markdown preview for example. If you hover over a sub-heading, you'll get a shortlink to that section: https://github.com/TypeRocket/docs/blob/main/v5/configuration.md

**Comment by kevindees** [comment]
Added
