### ISSUE TITLE
scroll to section animation is distracting

### ISSUE THREAD

**Issue by jdoubleu** [TypeRocket/docs#7]
I find the "scroll to section" animation very distracting. When you click on a link in the _table of contents_ and get taken to that section, the section header wiggles from left to right.

For me, that totally breaks my reading flow.

I would suggest to use some unobtrusive animation or none at all. One animation I could think of, is just to flash the background (in yellow) for a second. The Laravel documentation uses no animation, for example: https://laravel.com/docs/8.x/installation#initial-configuration

**Comment by kevindees** [comment]
fixed
